PREFIX : <http://www.oxfordsemantic.tech/f1demo/>

SELECT ?forename ?surname
WHERE {
    ?driver a :DriverWithoutPodiums ;
        :drivers_forename ?forename ;
        :drivers_surname ?surname .
}
LIMIT 10