PREFIX : <http://www.oxfordsemantic.tech/f1demo/>

SELECT ?forename ?surname ?percentage
WHERE {
    ?driver :drivers_forename ?forename;
        :drivers_surname ?surname;
        :hasWinPercentage ?percentage;
        :hasRaceCount ?count .
    FILTER(?count > 10)
}
ORDER BY DESC(?percentage)
LIMIT 10