#Query 16
PREFIX : <https://rdfox.com/examples/f1/>

SELECT ?forename ?surname ?count
WHERE {
    ?driver :hasRaceCount ?count ;
        :driver_forename ?forename ;
        :driver_surname ?surname .
}
ORDER BY DESC(?count)
LIMIT 10