#Query 17
PREFIX : <https://rdfox.com/examples/f1/>

SELECT ?forename ?surname ?count ?winCount
WHERE {
    ?driver :driver_forename ?forename ;
        :driver_surname ?surname ;
        :hasRaceCount ?count ;
        :hasRaceWinCount ?winCount .
}
ORDER BY DESC(?winCount)
LIMIT 10
