#Query 18
PREFIX : <https://rdfox.com/examples/f1/>

SELECT ?forename ?surname
WHERE {
    ?driver a :DriverWithoutPodiums ;
        :driver_forename ?forename ;
        :driver_surname ?surname .
}
LIMIT 10