PREFIX : <http://www.oxfordsemantic.tech/f1demo/>

# Can you return everything about a specific driver, say Lewis Hamilton?
SELECT ?driver ?p ?o
WHERE {
  ?driver a :driver ;
          :driver_forename "Lewis" ;
          :driver_surname "Hamilton" ;
          ?p ?o .
}