#Query 7
PREFIX : <https://rdfox.com/examples/f1/>

# Number of races Lewis Hamilton raced
SELECT (COUNT(?race) AS ?raceCount)
WHERE {
  
  ?driver :driver_forename "Lewis" ;
          :driver_surname "Hamilton" .
          
  ?result :result_driver ?driver ;
          :result_race ?race .

}