# Query 7

# Number of races Lewis Hamilton has raced in
SELECT (COUNT(?race) AS ?raceCount)
WHERE {
  
  ?driver :driver_forename "Lewis" ;
    :driver_surname "Hamilton" .
          
  ?result :result_driver ?driver ;
    :result_race ?race .
}