#Query 8
PREFIX : <http://www.oxfordsemantic.tech/f1demo/>

# Number of races per driver, ordered
SELECT ?driver (COUNT(?race) AS ?raceCount)
WHERE {
  ?result :result_driver ?driver ;
          :result_race ?race .
}
GROUP BY ?driver
ORDER BY DESC(?raceCount)