#Query 8, Bonus 1
PREFIX : <https://rdfox.com/examples/f1/>

# Number of races per driver, ordered
SELECT ?forename ?surname (COUNT(?race) AS ?raceCount)
WHERE {
  ?driver :driver_forename ?forename ;
          :driver_surname ?surname .

  ?result :result_driver ?driver ;
          :result_race ?race .  
}
GROUP BY ?driver
ORDER BY DESC(?raceCount)