PREFIX : <http://www.oxfordsemantic.tech/f1demo/>

SELECT ?forename ?surname ?race_name ?race_year
WHERE {
    ?driver :hasPodiumInRace ?race ;
        :drivers_forename ?forename ;
        :drivers_surname ?surname .

    ?race :races_name ?race_name ;
        :races_year ?race_year .
}
LIMIT 10